sudo: required
services:
  - docker
script:
  - docker run -v .:/app wongni/golang-k8s-testenv make test
after_success:
  - docker run -v .:/app wongni/golang-k8s-testenv make
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-603244702495
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
